//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOfDarksky_Bence_Szalma.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestOfDarksky_Bence_Szalma.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érezhető hőmérséklet.
        /// </summary>
        public static string ApparentTemperatureText {
            get {
                return ResourceManager.GetString("ApparentTemperatureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string HumidityMeas {
            get {
                return ResourceManager.GetString("HumidityMeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páratartam.
        /// </summary>
        public static string HumidityText {
            get {
                return ResourceManager.GetString("HumidityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válassza ki az aplikáció nyelvezetét.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hPa.
        /// </summary>
        public static string PressureMeas {
            get {
                return ResourceManager.GetString("PressureMeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyomás.
        /// </summary>
        public static string PressureText {
            get {
                return ResourceManager.GetString("PressureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C,km/h.
        /// </summary>
        public static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string TemperatureMeas {
            get {
                return ResourceManager.GetString("TemperatureMeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hőmérséklet.
        /// </summary>
        public static string TemperatureText {
            get {
                return ResourceManager.GetString("TemperatureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F,mph.
        /// </summary>
        public static string us {
            get {
                return ResourceManager.GetString("us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UvIndexMeas {
            get {
                return ResourceManager.GetString("UvIndexMeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uv Index.
        /// </summary>
        public static string UvIndexText {
            get {
                return ResourceManager.GetString("UvIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez az aplikáció a Docler Holding nevű cég &quot;felvételi&quot; teszt aplikációja, kérem az őszinte viszajelzését, az applikációval kapcsolatban.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kph.
        /// </summary>
        public static string WindSpeedMeas {
            get {
                return ResourceManager.GetString("WindSpeedMeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szélsebesség.
        /// </summary>
        public static string WindSpeedText {
            get {
                return ResourceManager.GetString("WindSpeedText", resourceCulture);
            }
        }
    }
}
